import 'dotenv/config'
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// Configuración de inferencia local por defecto
const DEFAULT_INFERENCE_CONFIG = {
  inputShape: JSON.stringify({ width: 640, height: 640, channels: 3 }),
  preprocessing: JSON.stringify({
    mean: [0, 0, 0],
    std: [1, 1, 1],
    normalize: true,
    channelOrder: 'RGB'
  }),
  postprocessing: JSON.stringify({
    confidenceThreshold: 0.5,
    iouThreshold: 0.45,
    maxDetections: 100
  }),
}

const SEED_MODELS = [
  // Seguridad - Modelos con ONNX disponible para demo
  {
    title: "Safety-Helmet-Detection",
    slug: "safety-helmet-detection",
    creator: "vision-experts-pne",
    description: "Detecta el uso de cascos de seguridad en entornos industriales. Ideal para monitoreo de cumplimiento de PPE en tiempo real.",
    category: "Seguridad",
    technical: "Detection",
    mAP: 0.945,
    precision: 0.912,
    inferenceMs: 14,
    image: "https://images.unsplash.com/photo-1590674899484-d564b18863bc?w=800&q=80",
    tags: JSON.stringify(["PPE", "Safety", "Construction", "Industrial"]),
    roboflowId: "hardhat-v3",
    version: "1.2.0",
    // Campos de inferencia local - Este modelo está listo para ONNX
    modelFormat: "onnx",
    onnxModelUrl: null, // Se establecerá cuando se suba un modelo real
    modelSizeBytes: null,
    labels: JSON.stringify(["helmet", "head", "person"]),
    ...DEFAULT_INFERENCE_CONFIG,
    isPremium: false,
    apiAccessTier: "free"
  },
  {
    title: "High-Vis-Vest-Monitor",
    slug: "high-vis-vest-monitor",
    creator: "safety-ai-labs",
    description: "Detecta chalecos reflectantes de alta visibilidad en trabajadores.",
    category: "Seguridad",
    technical: "Detection",
    mAP: 0.923,
    precision: 0.89,
    inferenceMs: 12,
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80",
    tags: JSON.stringify(["PPE", "Visibility", "Safety"]),
    roboflowId: "high-vis-vest",
    version: "1.0.0",
    modelFormat: "onnx",
    onnxModelUrl: null,
    modelSizeBytes: null,
    labels: JSON.stringify(["vest", "no-vest", "person"]),
    ...DEFAULT_INFERENCE_CONFIG,
    isPremium: false,
    apiAccessTier: "free"
  },
  {
    title: "Exclusion-Zone-Monitor",
    slug: "exclusion-zone-monitor",
    creator: "industrial-vision",
    description: "Monitorea zonas de exclusión y detecta intrusiones no autorizadas.",
    category: "Seguridad",
    technical: "Detection",
    mAP: 0.891,
    precision: 0.87,
    inferenceMs: 18,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
    tags: JSON.stringify(["Intrusion", "Perimeter", "Security"]),
    roboflowId: "exclusion-zone",
    version: "1.1.0"
  },
  {
    title: "Ergonomic-Posture-Check",
    slug: "ergonomic-posture-check",
    creator: "health-ai",
    description: "Analiza la postura ergonómica de trabajadores para prevenir lesiones.",
    category: "Seguridad",
    technical: "Keypoint",
    mAP: 0.876,
    precision: 0.85,
    inferenceMs: 22,
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400",
    tags: JSON.stringify(["Ergonomics", "Posture", "Health"]),
    roboflowId: "posture-check",
    version: "1.0.0"
  },
  // Calidad
  {
    title: "Industrial-Surface-Defects",
    slug: "industrial-surface-defects",
    creator: "quality-vision",
    description: "Detecta defectos en superficies industriales como rayones, abolladuras y manchas.",
    category: "Calidad",
    technical: "Segmentation",
    mAP: 0.934,
    precision: 0.91,
    inferenceMs: 25,
    image: "https://images.unsplash.com/photo-1504917595217-d4dc5f643038?w=800&q=80",
    tags: JSON.stringify(["Defects", "Quality", "Manufacturing"]),
    roboflowId: "surface-defects",
    version: "2.0.0"
  },
  {
    title: "PCB-Solder-Inspector",
    slug: "pcb-solder-inspector",
    creator: "electronics-ai",
    description: "Inspecciona soldaduras en placas PCB para detectar defectos.",
    category: "Calidad",
    technical: "Detection",
    mAP: 0.956,
    precision: 0.94,
    inferenceMs: 16,
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80",
    tags: JSON.stringify(["PCB", "Electronics", "Solder"]),
    roboflowId: "pcb-solder",
    version: "1.3.0",
    modelFormat: "onnx",
    onnxModelUrl: null,
    modelSizeBytes: null,
    labels: JSON.stringify(["good_solder", "cold_solder", "bridge", "missing", "excess"]),
    ...DEFAULT_INFERENCE_CONFIG,
    isPremium: true,
    apiAccessTier: "basic"
  },
  {
    title: "Glass-Bottle-Fracture",
    slug: "glass-bottle-fracture",
    creator: "packaging-vision",
    description: "Detecta fracturas y defectos en botellas de vidrio.",
    category: "Calidad",
    technical: "Detection",
    mAP: 0.912,
    precision: 0.88,
    inferenceMs: 14,
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400",
    tags: JSON.stringify(["Glass", "Packaging", "Defects"]),
    roboflowId: "glass-fracture",
    version: "1.0.0"
  },
  {
    title: "QR-Label-Verifier",
    slug: "qr-label-verifier",
    creator: "logistics-ai",
    description: "Verifica la legibilidad y posición correcta de códigos QR en etiquetas.",
    category: "Calidad",
    technical: "Detection",
    mAP: 0.978,
    precision: 0.96,
    inferenceMs: 8,
    image: "https://images.unsplash.com/photo-1595079676339-1534801ad6cf?w=400",
    tags: JSON.stringify(["QR", "Labels", "Verification"]),
    roboflowId: "qr-verifier",
    version: "1.1.0"
  },
  // Operacional
  {
    title: "Pallet-Volume-Estimator",
    slug: "pallet-volume-estimator",
    creator: "warehouse-ai",
    description: "Estima el volumen de carga en pallets para optimizar logística.",
    category: "Operacional",
    technical: "Detection",
    mAP: 0.887,
    precision: 0.86,
    inferenceMs: 20,
    image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=400",
    tags: JSON.stringify(["Warehouse", "Pallets", "Logistics"]),
    roboflowId: "pallet-volume",
    version: "1.0.0"
  },
  {
    title: "Conveyor-Belt-Sorter",
    slug: "conveyor-belt-sorter",
    creator: "automation-vision",
    description: "Clasifica objetos en cintas transportadoras para automatización.",
    category: "Operacional",
    technical: "Classification",
    mAP: 0.923,
    precision: 0.90,
    inferenceMs: 11,
    image: "https://images.unsplash.com/photo-1567789884554-0b844b597180?w=400",
    tags: JSON.stringify(["Conveyor", "Sorting", "Automation"]),
    roboflowId: "conveyor-sorter",
    version: "1.2.0"
  },
  {
    title: "Warehouse-Safety-Monitor",
    slug: "warehouse-safety-monitor",
    creator: "safety-ai-labs",
    description: "Monitorea la seguridad general en almacenes: montacargas, peatones, obstrucciones.",
    category: "Operacional",
    technical: "Detection",
    mAP: 0.901,
    precision: 0.87,
    inferenceMs: 18,
    image: "https://images.unsplash.com/photo-1553413077-190dd305871c?w=400",
    tags: JSON.stringify(["Warehouse", "Safety", "Forklift"]),
    roboflowId: "warehouse-safety",
    version: "1.0.0"
  },
  {
    title: "Tool-Tracker",
    slug: "tool-tracker",
    creator: "industrial-vision",
    description: "Rastrea herramientas en el área de trabajo para inventario y seguridad.",
    category: "Operacional",
    technical: "Detection",
    mAP: 0.867,
    precision: 0.84,
    inferenceMs: 15,
    image: "https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=400",
    tags: JSON.stringify(["Tools", "Inventory", "Tracking"]),
    roboflowId: "tool-tracker",
    version: "1.0.0"
  },
  // Salud
  {
    title: "Scrub-Nurse-Counter",
    slug: "scrub-nurse-counter",
    creator: "medical-ai",
    description: "Cuenta personal médico en quirófanos para cumplimiento de protocolos.",
    category: "Salud",
    technical: "Detection",
    mAP: 0.912,
    precision: 0.89,
    inferenceMs: 16,
    image: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=400",
    tags: JSON.stringify(["Medical", "Hospital", "Staff"]),
    roboflowId: "scrub-counter",
    version: "1.0.0"
  },
  {
    title: "Fall-Watch-Elderly",
    slug: "fall-watch-elderly",
    creator: "health-ai",
    description: "Detecta caídas de personas mayores para alerta temprana.",
    category: "Salud",
    technical: "Detection",
    mAP: 0.934,
    precision: 0.91,
    inferenceMs: 12,
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=400",
    tags: JSON.stringify(["Fall", "Elderly", "Alert"]),
    roboflowId: "fall-detection",
    version: "1.1.0",
    modelFormat: "onnx",
    onnxModelUrl: null,
    modelSizeBytes: null,
    labels: JSON.stringify(["standing", "sitting", "lying", "falling"]),
    ...DEFAULT_INFERENCE_CONFIG,
    isPremium: true,
    apiAccessTier: "pro"
  },
  {
    title: "CT-Scan-Anomaly",
    slug: "ct-scan-anomaly",
    creator: "radiology-ai",
    description: "Detecta anomalías en tomografías computarizadas.",
    category: "Salud",
    technical: "Segmentation",
    mAP: 0.889,
    precision: 0.86,
    inferenceMs: 45,
    image: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400",
    tags: JSON.stringify(["CT", "Radiology", "Medical"]),
    roboflowId: "ct-anomaly",
    version: "1.0.0"
  },
  {
    title: "Medication-Pill-Sorter",
    slug: "medication-pill-sorter",
    creator: "pharma-vision",
    description: "Clasifica y cuenta medicamentos para control de inventario.",
    category: "Salud",
    technical: "Classification",
    mAP: 0.956,
    precision: 0.94,
    inferenceMs: 10,
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400",
    tags: JSON.stringify(["Medication", "Pharmacy", "Sorting"]),
    roboflowId: "pill-sorter",
    version: "1.2.0"
  },
  // Retail
  {
    title: "Store-Queue-Manager",
    slug: "store-queue-manager",
    creator: "retail-ai",
    description: "Monitorea filas en tiendas y estima tiempos de espera.",
    category: "Retail",
    technical: "Detection",
    mAP: 0.901,
    precision: 0.88,
    inferenceMs: 14,
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80",
    tags: JSON.stringify(["Queue", "Retail", "Customer"]),
    roboflowId: "queue-manager",
    version: "1.0.0"
  },
  {
    title: "Shoplift-Action-Detector",
    slug: "shoplift-action-detector",
    creator: "security-vision",
    description: "Detecta comportamientos sospechosos de hurto en tiendas.",
    category: "Retail",
    technical: "Detection",
    mAP: 0.823,
    precision: 0.79,
    inferenceMs: 22,
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400",
    tags: JSON.stringify(["Security", "Retail", "Loss Prevention"]),
    roboflowId: "shoplift-detector",
    version: "1.0.0"
  },
  {
    title: "Brand-Engagement-Tracker",
    slug: "brand-engagement-tracker",
    creator: "marketing-ai",
    description: "Rastrea interacciones de clientes con displays de marca.",
    category: "Retail",
    technical: "Detection",
    mAP: 0.856,
    precision: 0.83,
    inferenceMs: 18,
    image: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=400",
    tags: JSON.stringify(["Marketing", "Engagement", "Analytics"]),
    roboflowId: "brand-tracker",
    version: "1.0.0"
  },
  {
    title: "In-Stock-Shelf-Monitor",
    slug: "in-stock-shelf-monitor",
    creator: "inventory-vision",
    description: "Detecta productos agotados en estantes de tienda.",
    category: "Retail",
    technical: "Detection",
    mAP: 0.912,
    precision: 0.89,
    inferenceMs: 16,
    image: "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=400",
    tags: JSON.stringify(["Inventory", "Shelf", "Stock"]),
    roboflowId: "shelf-monitor",
    version: "1.1.0"
  },
  // Mantenimiento / Infraestructura
  {
    title: "Dam-Crack-Inspector",
    slug: "dam-crack-inspector",
    creator: "infrastructure-ai",
    description: "Inspecciona presas y detecta grietas estructurales.",
    category: "Infraestructura",
    technical: "Segmentation",
    mAP: 0.878,
    precision: 0.85,
    inferenceMs: 28,
    image: "https://images.unsplash.com/photo-1509315811345-672d83ef2fbc?w=400",
    tags: JSON.stringify(["Dam", "Infrastructure", "Cracks"]),
    roboflowId: "dam-inspector",
    version: "1.0.0"
  },
  {
    title: "Pothole-Repair-Detector",
    slug: "pothole-repair-detector",
    creator: "road-vision",
    description: "Detecta baches en carreteras para mantenimiento vial.",
    category: "Infraestructura",
    technical: "Detection",
    mAP: 0.923,
    precision: 0.90,
    inferenceMs: 14,
    image: "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=400",
    tags: JSON.stringify(["Roads", "Maintenance", "Pothole"]),
    roboflowId: "pothole-detector",
    version: "1.2.0"
  },
  {
    title: "Railway-Track-Inspector",
    slug: "railway-track-inspector",
    creator: "rail-ai",
    description: "Inspecciona vías férreas para detectar defectos y obstrucciones.",
    category: "Infraestructura",
    technical: "Detection",
    mAP: 0.901,
    precision: 0.87,
    inferenceMs: 20,
    image: "https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=400",
    tags: JSON.stringify(["Railway", "Inspection", "Safety"]),
    roboflowId: "railway-inspector",
    version: "1.0.0"
  },
  {
    title: "Traffic-Signal-Monitor",
    slug: "traffic-signal-monitor",
    creator: "traffic-vision",
    description: "Monitorea el funcionamiento de semáforos y señales de tráfico.",
    category: "Infraestructura",
    technical: "Detection",
    mAP: 0.945,
    precision: 0.92,
    inferenceMs: 12,
    image: "https://images.unsplash.com/photo-1489824904134-891ab64532f1?w=400",
    tags: JSON.stringify(["Traffic", "Signals", "Urban"]),
    roboflowId: "traffic-monitor",
    version: "1.1.0"
  },
  // Energía
  {
    title: "Thermal-Solar-Panel",
    slug: "thermal-solar-panel",
    creator: "energy-ai",
    description: "Detecta puntos calientes en paneles solares mediante termografía.",
    category: "Energia",
    technical: "Segmentation",
    mAP: 0.889,
    precision: 0.86,
    inferenceMs: 22,
    image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=400",
    tags: JSON.stringify(["Solar", "Thermal", "Energy"]),
    roboflowId: "solar-thermal",
    version: "1.0.0"
  },
  {
    title: "High-Voltage-Arc-Watch",
    slug: "high-voltage-arc-watch",
    creator: "power-vision",
    description: "Detecta arcos eléctricos en equipos de alta tensión.",
    category: "Energia",
    technical: "Detection",
    mAP: 0.867,
    precision: 0.84,
    inferenceMs: 18,
    image: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=400",
    tags: JSON.stringify(["Electrical", "Arc", "Safety"]),
    roboflowId: "arc-detector",
    version: "1.0.0"
  },
  {
    title: "Grid-Insulator-Inspector",
    slug: "grid-insulator-inspector",
    creator: "utility-ai",
    description: "Inspecciona aisladores de líneas eléctricas para detectar daños.",
    category: "Energia",
    technical: "Detection",
    mAP: 0.912,
    precision: 0.89,
    inferenceMs: 16,
    image: "https://images.unsplash.com/photo-1548337138-e87d889cc369?w=400",
    tags: JSON.stringify(["Grid", "Insulators", "Power"]),
    roboflowId: "insulator-inspector",
    version: "1.1.0"
  },
  {
    title: "Wind-Turbine-Blade",
    slug: "wind-turbine-blade",
    creator: "wind-vision",
    description: "Detecta daños en aspas de turbinas eólicas.",
    category: "Energia",
    technical: "Segmentation",
    mAP: 0.878,
    precision: 0.85,
    inferenceMs: 30,
    image: "https://images.unsplash.com/photo-1532601224476-15c79f2f7a51?w=400",
    tags: JSON.stringify(["Wind", "Turbine", "Inspection"]),
    roboflowId: "turbine-blade",
    version: "1.0.0"
  },
  // Agricultura
  {
    title: "Berry-Size-Grader",
    slug: "berry-size-grader",
    creator: "agri-vision",
    description: "Clasifica bayas por tamaño para control de calidad agrícola.",
    category: "Agricultura",
    technical: "Classification",
    mAP: 0.934,
    precision: 0.91,
    inferenceMs: 10,
    image: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400",
    tags: JSON.stringify(["Berries", "Agriculture", "Grading"]),
    roboflowId: "berry-grader",
    version: "1.0.0"
  },
  {
    title: "Calf-Weight-Estimator",
    slug: "calf-weight-estimator",
    creator: "livestock-ai",
    description: "Estima el peso de terneros mediante análisis de imagen.",
    category: "Agricultura",
    technical: "Detection",
    mAP: 0.845,
    precision: 0.82,
    inferenceMs: 24,
    image: "https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=400",
    tags: JSON.stringify(["Livestock", "Weight", "Cattle"]),
    roboflowId: "calf-weight",
    version: "1.0.0"
  },
  {
    title: "Precision-Weeder",
    slug: "precision-weeder",
    creator: "crop-vision",
    description: "Identifica malezas para aplicación precisa de herbicidas.",
    category: "Agricultura",
    technical: "Segmentation",
    mAP: 0.912,
    precision: 0.89,
    inferenceMs: 18,
    image: "https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=400",
    tags: JSON.stringify(["Weeds", "Precision", "Agriculture"]),
    roboflowId: "precision-weeder",
    version: "1.1.0"
  },
  {
    title: "Top-Soil-Compaction",
    slug: "top-soil-compaction",
    creator: "soil-ai",
    description: "Analiza la compactación del suelo mediante imágenes.",
    category: "Agricultura",
    technical: "Segmentation",
    mAP: 0.823,
    precision: 0.80,
    inferenceMs: 26,
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400",
    tags: JSON.stringify(["Soil", "Agriculture", "Analysis"]),
    roboflowId: "soil-compaction",
    version: "1.0.0"
  },
  // Minería
  {
    title: "Belt-Material-Sizer",
    slug: "belt-material-sizer",
    creator: "mining-vision",
    description: "Mide el tamaño del material en cintas transportadoras de minas.",
    category: "Mineria",
    technical: "Segmentation",
    mAP: 0.878,
    precision: 0.85,
    inferenceMs: 20,
    image: "https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?w=400",
    tags: JSON.stringify(["Mining", "Material", "Sizing"]),
    roboflowId: "belt-sizer",
    version: "1.0.0"
  },
  {
    title: "Fleet-Tire-Monitor",
    slug: "fleet-tire-monitor",
    creator: "heavy-equipment-ai",
    description: "Monitorea el estado de neumáticos de vehículos mineros.",
    category: "Mineria",
    technical: "Detection",
    mAP: 0.901,
    precision: 0.87,
    inferenceMs: 16,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
    tags: JSON.stringify(["Fleet", "Tires", "Mining"]),
    roboflowId: "tire-monitor",
    version: "1.0.0"
  },
  {
    title: "Pit-Wall-Stability",
    slug: "pit-wall-stability",
    creator: "geotechnical-ai",
    description: "Analiza la estabilidad de paredes de minas a cielo abierto.",
    category: "Mineria",
    technical: "Segmentation",
    mAP: 0.856,
    precision: 0.83,
    inferenceMs: 32,
    image: "https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=400",
    tags: JSON.stringify(["Mining", "Stability", "Safety"]),
    roboflowId: "pit-wall",
    version: "1.0.0"
  },
  {
    title: "Rockfall-Detection",
    slug: "rockfall-detection",
    creator: "mining-safety-ai",
    description: "Detecta caídas de rocas en operaciones mineras.",
    category: "Mineria",
    technical: "Detection",
    mAP: 0.889,
    precision: 0.86,
    inferenceMs: 14,
    image: "https://images.unsplash.com/photo-1518391846015-55a9cc003b25?w=400",
    tags: JSON.stringify(["Rockfall", "Mining", "Safety"]),
    roboflowId: "rockfall-detector",
    version: "1.1.0"
  },
  // Manufactura
  {
    title: "Robotic-Arm-Safety",
    slug: "robotic-arm-safety",
    creator: "robotics-vision",
    description: "Monitorea zonas de seguridad alrededor de brazos robóticos.",
    category: "Manufactura",
    technical: "Detection",
    mAP: 0.934,
    precision: 0.91,
    inferenceMs: 10,
    image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400",
    tags: JSON.stringify(["Robotics", "Safety", "Manufacturing"]),
    roboflowId: "robotic-safety",
    version: "1.2.0"
  },
  {
    title: "Engine-Assembly-Checker",
    slug: "engine-assembly-checker",
    creator: "automotive-ai",
    description: "Verifica el ensamblaje correcto de componentes de motor.",
    category: "Manufactura",
    technical: "Detection",
    mAP: 0.956,
    precision: 0.94,
    inferenceMs: 18,
    image: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=400",
    tags: JSON.stringify(["Engine", "Assembly", "Automotive"]),
    roboflowId: "engine-checker",
    version: "1.0.0"
  },
  {
    title: "Gear-Tooth-Inspector",
    slug: "gear-tooth-inspector",
    creator: "precision-ai",
    description: "Inspecciona dientes de engranajes para detectar desgaste.",
    category: "Manufactura",
    technical: "Segmentation",
    mAP: 0.923,
    precision: 0.90,
    inferenceMs: 22,
    image: "https://images.unsplash.com/photo-1537462715879-360eeb61a0ad?w=400",
    tags: JSON.stringify(["Gears", "Inspection", "Precision"]),
    roboflowId: "gear-inspector",
    version: "1.0.0"
  }
]

async function main() {
  console.log('Start seeding...')

  for (const model of SEED_MODELS) {
    const created = await prisma.model.upsert({
      where: { slug: model.slug },
      update: model,
      create: model,
    })
    console.log(`Created model: ${created.title}`)
  }

  console.log('Seeding finished.')
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
