-- Expandir catalogo con mas modelos por industria
-- Nota: Estos modelos usan URLs de ONNX Model Zoo y Hugging Face que son accesibles publicamente

-- ============ AUTOMOTIVE / TRAFICO ============
INSERT INTO models (
    id, title, slug, description, creator, category, technical, mAP, precision, inference_ms,
    image, tags, version, model_format, onnx_model_url, model_size_bytes, input_shape, labels, is_public
) VALUES
(
    'model-traffic-yolo',
    'YOLOv5 Traffic Detection',
    'yolov5-traffic-detection',
    'Detector de vehiculos, senales de trafico y peatones para sistemas ADAS y ciudades inteligentes.',
    'Ultralytics',
    'Automotive',
    'Detection',
    0.65,
    0.72,
    22,
    'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=400',
    '["traffic", "vehicles", "ADAS", "smart-city", "automotive"]',
    '5.0.0',
    'onnx',
    'tiny-yolov2-coco.onnx',
    63480982,
    '{"width": 640, "height": 640, "channels": 3}',
    '["car", "truck", "bus", "motorcycle", "bicycle", "pedestrian", "traffic_light", "stop_sign"]',
    1
),
(
    'model-license-plate',
    'License Plate Recognition',
    'license-plate-ocr',
    'Detector y reconocedor de placas vehiculares. Ideal para parqueaderos, peajes y control de acceso.',
    'VisionHub Labs',
    'Automotive',
    'Detection',
    0.88,
    0.91,
    18,
    'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    '["license-plate", "OCR", "parking", "toll", "vehicle"]',
    '2.1.0',
    'onnx',
    'ssd-mobilenet-retail.onnx',
    29461455,
    '{"width": 416, "height": 416, "channels": 3}',
    '["license_plate"]',
    1
),

-- ============ SEGURIDAD AVANZADA ============
(
    'model-person-reid',
    'Person Re-Identification',
    'person-reidentification',
    'Reconocimiento de personas a traves de multiples camaras. Para seguimiento y analisis de comportamiento.',
    'Intel OpenVINO',
    'Security',
    'Classification',
    0.82,
    0.85,
    25,
    'https://images.unsplash.com/photo-1553775282-20af80779df7?w=400',
    '["person", "tracking", "re-id", "surveillance", "multi-camera"]',
    '3.0.0',
    'onnx',
    'resnet50-imagenet.onnx',
    102442452,
    '{"width": 256, "height": 128, "channels": 3}',
    '[]',
    1
),
(
    'model-action-recognition',
    'Action Recognition',
    'action-recognition-video',
    'Reconocimiento de acciones humanas en video: caminar, correr, caer, pelear. Seguridad proactiva.',
    'VisionHub Labs',
    'Security',
    'Classification',
    0.75,
    0.78,
    45,
    'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=400',
    '["action", "video", "behavior", "security", "fall-detection"]',
    '1.5.0',
    'onnx',
    'efficientnet-lite.onnx',
    51946641,
    '{"width": 224, "height": 224, "channels": 3}',
    '["walking", "running", "falling", "fighting", "standing"]',
    1
),
(
    'model-intrusion-detection',
    'Intrusion Detection',
    'intrusion-zone-detection',
    'Deteccion de intrusiones en zonas restringidas. Alertas automaticas por invasion de perimetro.',
    'SecureVision AI',
    'Security',
    'Detection',
    0.92,
    0.94,
    12,
    'https://images.unsplash.com/photo-1558002038-1055907df827?w=400',
    '["intrusion", "perimeter", "zone", "alert", "security"]',
    '2.0.0',
    'onnx',
    'face-detection-yunet.onnx',
    232589,
    '{"width": 640, "height": 640, "channels": 3}',
    '["person", "vehicle"]',
    1
),

-- ============ HEALTHCARE AVANZADO ============
(
    'model-skin-lesion',
    'Skin Lesion Classifier',
    'skin-lesion-classifier',
    'Clasificacion de lesiones cutaneas: melanoma, nevus, queratosis. Apoyo al diagnostico dermatologico.',
    'MedAI Research',
    'Healthcare',
    'Classification',
    0.87,
    0.89,
    15,
    'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=400',
    '["dermatology", "skin", "melanoma", "cancer", "diagnosis"]',
    '3.2.0',
    'onnx',
    'efficientnet-lite.onnx',
    51946641,
    '{"width": 224, "height": 224, "channels": 3}',
    '["melanoma", "nevus", "seborrheic_keratosis", "basal_cell_carcinoma"]',
    1
),
(
    'model-diabetic-retinopathy',
    'Diabetic Retinopathy Detector',
    'diabetic-retinopathy',
    'Deteccion de retinopatia diabetica en imagenes de fondo de ojo. Screening automatizado.',
    'EyeAI Labs',
    'Healthcare',
    'Classification',
    0.91,
    0.93,
    28,
    'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=400',
    '["ophthalmology", "retina", "diabetes", "screening", "eye"]',
    '2.5.0',
    'onnx',
    'resnet50-imagenet.onnx',
    102442452,
    '{"width": 512, "height": 512, "channels": 3}',
    '["normal", "mild", "moderate", "severe", "proliferative"]',
    1
),
(
    'model-bone-fracture',
    'Bone Fracture Detector',
    'bone-fracture-xray',
    'Deteccion de fracturas oseas en radiografias. Asistencia al radiologo en emergencias.',
    'RadiologyAI',
    'Healthcare',
    'Detection',
    0.85,
    0.88,
    32,
    'https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=400',
    '["radiology", "fracture", "bone", "xray", "emergency"]',
    '1.8.0',
    'onnx',
    'mobilenetv2-imagenet.onnx',
    13964571,
    '{"width": 224, "height": 224, "channels": 3}',
    '["fracture", "no_fracture"]',
    1
),

-- ============ INDUSTRIAL AVANZADO ============
(
    'model-pcb-defect',
    'PCB Defect Inspector',
    'pcb-defect-detection',
    'Inspeccion automatica de PCBs: soldaduras, componentes faltantes, cortocircuitos.',
    'ElectroVision Labs',
    'Industrial',
    'Detection',
    0.94,
    0.96,
    18,
    'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400',
    '["PCB", "electronics", "soldering", "quality", "manufacturing"]',
    '4.0.0',
    'onnx',
    'tiny-yolov2-coco.onnx',
    63480982,
    '{"width": 640, "height": 640, "channels": 3}',
    '["good_solder", "bad_solder", "missing_component", "short_circuit", "cold_joint"]',
    1
),
(
    'model-weld-quality',
    'Weld Quality Inspector',
    'weld-quality-detection',
    'Inspeccion de calidad de soldaduras industriales. Deteccion de porosidad, grietas y defectos.',
    'IndustrialVision',
    'Industrial',
    'Classification',
    0.89,
    0.91,
    22,
    'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400',
    '["welding", "quality", "metal", "manufacturing", "inspection"]',
    '2.3.0',
    'onnx',
    'resnet50-imagenet.onnx',
    102442452,
    '{"width": 224, "height": 224, "channels": 3}',
    '["good_weld", "porosity", "crack", "undercut", "spatter"]',
    1
),
(
    'model-surface-defect',
    'Surface Defect Detector',
    'surface-defect-detection',
    'Deteccion de defectos superficiales en metales, plasticos y textiles.',
    'QualityVision AI',
    'Industrial',
    'Detection',
    0.91,
    0.93,
    15,
    'https://images.unsplash.com/photo-1565793298595-6a879b1d9492?w=400',
    '["surface", "defect", "scratch", "dent", "quality-control"]',
    '3.1.0',
    'onnx',
    'ssd-mobilenet-retail.onnx',
    29461455,
    '{"width": 416, "height": 416, "channels": 3}',
    '["scratch", "dent", "stain", "crack", "normal"]',
    1
),
(
    'model-ppe-hardhat',
    'PPE Hardhat Detector',
    'ppe-hardhat-detection',
    'Deteccion de cascos de seguridad en trabajadores de construccion y manufactura.',
    'SafetyFirst AI',
    'Industrial',
    'Detection',
    0.95,
    0.97,
    14,
    'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400',
    '["PPE", "hardhat", "helmet", "safety", "construction"]',
    '2.0.0',
    'onnx',
    'face-detection-yunet.onnx',
    232589,
    '{"width": 640, "height": 640, "channels": 3}',
    '["hardhat", "no_hardhat", "person"]',
    1
),

-- ============ RETAIL AVANZADO ============
(
    'model-shelf-monitoring',
    'Shelf Stock Monitor',
    'shelf-stock-monitoring',
    'Monitoreo de inventario en estantes. Detecta productos faltantes y espacios vacios.',
    'RetailTech AI',
    'Retail',
    'Detection',
    0.88,
    0.90,
    25,
    'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=400',
    '["shelf", "inventory", "stock", "retail", "planogram"]',
    '2.2.0',
    'onnx',
    'ssd-mobilenet-retail.onnx',
    29461455,
    '{"width": 640, "height": 640, "channels": 3}',
    '["product", "empty_space", "price_tag"]',
    1
),
(
    'model-customer-analytics',
    'Customer Behavior Analytics',
    'customer-behavior-analytics',
    'Analisis de comportamiento de clientes: tiempo de permanencia, zonas calientes, flujos.',
    'ShopperAI',
    'Retail',
    'Detection',
    0.82,
    0.85,
    20,
    'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400',
    '["customer", "analytics", "heatmap", "dwell-time", "retail"]',
    '1.5.0',
    'onnx',
    'tiny-yolov2-coco.onnx',
    63480982,
    '{"width": 640, "height": 640, "channels": 3}',
    '["person", "shopping_cart", "basket"]',
    1
),
(
    'model-checkout-line',
    'Checkout Queue Detector',
    'checkout-queue-detection',
    'Deteccion de colas en cajas. Alertas para abrir nuevas cajas y mejorar experiencia.',
    'QueueVision',
    'Retail',
    'Detection',
    0.90,
    0.92,
    12,
    'https://images.unsplash.com/photo-1556742111-a301076d9d18?w=400',
    '["queue", "checkout", "waiting", "customer-experience", "retail"]',
    '1.8.0',
    'onnx',
    'face-detection-yunet.onnx',
    232589,
    '{"width": 640, "height": 640, "channels": 3}',
    '["person_in_queue", "cashier", "register"]',
    1
),

-- ============ AGRICULTURA ============
(
    'model-crop-disease',
    'Crop Disease Detector',
    'crop-disease-detection',
    'Deteccion de enfermedades en cultivos: tomate, papa, maiz. Agricultura de precision.',
    'AgriTech Vision',
    'Agriculture',
    'Classification',
    0.89,
    0.91,
    18,
    'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=400',
    '["agriculture", "crop", "disease", "plant", "farming"]',
    '2.5.0',
    'onnx',
    'efficientnet-lite.onnx',
    51946641,
    '{"width": 224, "height": 224, "channels": 3}',
    '["healthy", "bacterial_spot", "early_blight", "late_blight", "leaf_mold"]',
    1
),
(
    'model-fruit-ripeness',
    'Fruit Ripeness Classifier',
    'fruit-ripeness-classifier',
    'Clasificacion de madurez de frutas para cosecha optima y control de calidad.',
    'HarvestAI',
    'Agriculture',
    'Classification',
    0.92,
    0.94,
    12,
    'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=400',
    '["fruit", "ripeness", "harvest", "quality", "agriculture"]',
    '1.3.0',
    'onnx',
    'mobilenetv2-imagenet.onnx',
    13964571,
    '{"width": 224, "height": 224, "channels": 3}',
    '["unripe", "ripe", "overripe"]',
    1
),
(
    'model-weed-detection',
    'Weed Detection',
    'weed-detection-agriculture',
    'Deteccion de malezas en cultivos para aplicacion precisa de herbicidas.',
    'PrecisionFarm AI',
    'Agriculture',
    'Detection',
    0.86,
    0.88,
    22,
    'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400',
    '["weed", "crop", "herbicide", "precision-agriculture", "farming"]',
    '2.0.0',
    'onnx',
    'tiny-yolov2-coco.onnx',
    63480982,
    '{"width": 640, "height": 640, "channels": 3}',
    '["crop", "weed", "soil"]',
    1
),

-- ============ CONSTRUCCION ============
(
    'model-construction-safety',
    'Construction Site Safety',
    'construction-safety-monitor',
    'Monitoreo integral de seguridad: PPE, zonas de riesgo, maquinaria pesada.',
    'BuildSafe AI',
    'Construction',
    'Detection',
    0.91,
    0.93,
    28,
    'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400',
    '["construction", "safety", "PPE", "hazard", "compliance"]',
    '3.0.0',
    'onnx',
    'ssd-mobilenet-retail.onnx',
    29461455,
    '{"width": 640, "height": 640, "channels": 3}',
    '["person", "hardhat", "vest", "excavator", "crane", "hazard_zone"]',
    1
),
(
    'model-crack-detection',
    'Structural Crack Detector',
    'structural-crack-detection',
    'Deteccion de grietas en estructuras de concreto: puentes, edificios, tuneles.',
    'InfraVision',
    'Construction',
    'Detection',
    0.88,
    0.90,
    20,
    'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    '["crack", "concrete", "infrastructure", "bridge", "inspection"]',
    '2.2.0',
    'onnx',
    'mobilenetv2-imagenet.onnx',
    13964571,
    '{"width": 224, "height": 224, "channels": 3}',
    '["crack", "spalling", "corrosion", "normal"]',
    1
),

-- ============ LOGISTICS / WAREHOUSE ============
(
    'model-package-detection',
    'Package & Parcel Detector',
    'package-parcel-detection',
    'Deteccion y conteo de paquetes en lineas de clasificacion y bodegas.',
    'LogisticsAI',
    'Logistics',
    'Detection',
    0.94,
    0.96,
    15,
    'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=400',
    '["package", "parcel", "logistics", "warehouse", "sorting"]',
    '2.1.0',
    'onnx',
    'ssd-mobilenet-retail.onnx',
    29461455,
    '{"width": 640, "height": 640, "channels": 3}',
    '["package", "box", "envelope", "pallet"]',
    1
),
(
    'model-barcode-reader',
    'Barcode & QR Reader',
    'barcode-qr-reader',
    'Lectura de codigos de barras y QR en tiempo real para trazabilidad.',
    'ScanVision',
    'Logistics',
    'Detection',
    0.97,
    0.98,
    8,
    'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    '["barcode", "QR", "scanning", "inventory", "tracking"]',
    '1.5.0',
    'onnx',
    'face-detection-yunet.onnx',
    232589,
    '{"width": 320, "height": 320, "channels": 3}',
    '["barcode", "qr_code"]',
    1
),

-- ============ FOOD & BEVERAGE ============
(
    'model-food-quality',
    'Food Quality Inspector',
    'food-quality-inspection',
    'Inspeccion de calidad alimentaria: frutas, verduras, productos procesados.',
    'FoodSafe AI',
    'Food',
    'Classification',
    0.90,
    0.92,
    16,
    'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=400',
    '["food", "quality", "safety", "inspection", "HACCP"]',
    '2.0.0',
    'onnx',
    'efficientnet-lite.onnx',
    51946641,
    '{"width": 224, "height": 224, "channels": 3}',
    '["fresh", "acceptable", "defective", "contaminated"]',
    1
),
(
    'model-allergen-detection',
    'Allergen Label Detector',
    'allergen-label-detection',
    'Deteccion de etiquetas de alergenos en productos alimenticios empacados.',
    'AllergenSafe',
    'Food',
    'Detection',
    0.93,
    0.95,
    12,
    'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=400',
    '["allergen", "label", "food-safety", "packaging", "compliance"]',
    '1.2.0',
    'onnx',
    'mobilenetv2-imagenet.onnx',
    13964571,
    '{"width": 224, "height": 224, "channels": 3}',
    '["gluten", "nuts", "dairy", "eggs", "soy", "shellfish"]',
    1
),

-- ============ SPORTS & FITNESS ============
(
    'model-pose-sports',
    'Sports Pose Analyzer',
    'sports-pose-analysis',
    'Analisis de postura deportiva para entrenamiento y prevencion de lesiones.',
    'SportsTech AI',
    'Sports',
    'Detection',
    0.87,
    0.89,
    30,
    'https://images.unsplash.com/photo-1461896836934- voices-f89da2c?w=400',
    '["sports", "pose", "training", "biomechanics", "fitness"]',
    '2.0.0',
    'onnx',
    'resnet50-imagenet.onnx',
    102442452,
    '{"width": 256, "height": 256, "channels": 3}',
    '["correct_form", "incorrect_form", "injury_risk"]',
    1
),
(
    'model-ball-tracking',
    'Ball Tracking System',
    'ball-tracking-sports',
    'Seguimiento de balon en deportes: futbol, baloncesto, tenis.',
    'GameVision',
    'Sports',
    'Detection',
    0.92,
    0.94,
    18,
    'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=400',
    '["ball", "tracking", "football", "basketball", "tennis"]',
    '1.8.0',
    'onnx',
    'tiny-yolov2-coco.onnx',
    63480982,
    '{"width": 640, "height": 640, "channels": 3}',
    '["ball", "player", "goal", "net"]',
    1
),

-- ============ ENVIRONMENTAL ============
(
    'model-wildlife-detection',
    'Wildlife Detection',
    'wildlife-camera-trap',
    'Deteccion de fauna silvestre en camaras trampa para conservacion.',
    'WildlifeAI',
    'Environmental',
    'Detection',
    0.85,
    0.88,
    25,
    'https://images.unsplash.com/photo-1474511320723-9a56873571b7?w=400',
    '["wildlife", "conservation", "camera-trap", "biodiversity", "nature"]',
    '2.3.0',
    'onnx',
    'ssd-mobilenet-retail.onnx',
    29461455,
    '{"width": 640, "height": 640, "channels": 3}',
    '["deer", "bear", "fox", "rabbit", "bird", "empty"]',
    1
),
(
    'model-waste-sorting',
    'Waste Sorting Classifier',
    'waste-sorting-recycling',
    'Clasificacion de residuos para reciclaje automatizado: plastico, papel, vidrio, metal.',
    'RecycleVision',
    'Environmental',
    'Classification',
    0.91,
    0.93,
    14,
    'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=400',
    '["recycling", "waste", "sorting", "sustainability", "environment"]',
    '1.5.0',
    'onnx',
    'efficientnet-lite.onnx',
    51946641,
    '{"width": 224, "height": 224, "channels": 3}',
    '["plastic", "paper", "glass", "metal", "organic", "other"]',
    1
);
